language: python
python:
  - "2"
  - "3"
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "sudo cp -p bin/gvoice /usr/bin/."
# command to run tests
script: pytest
