dist: trusty # trusty = ubuntu 14.04
sudo: false # false = docker container environment
language: python
python:
  - "2.7"
  - "nightly" # currently points to 3.9-dev
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "sudo cp -p bin/gvoice /usr/bin/."
# command to run tests
script: pytest
